# Dockerfile for development of yarn-based application

# Use the official image as a parent image
FROM docker.io/library/node:22.18.0

# Set the working directory
WORKDIR /usr/src/app

# Define environment variables
ENV YARN_VERSION 4.8.1
ENV YARN_CACHE_FOLDER=/cache/yarn

# Install Yarn
RUN corepack enable && \
    yarn set version $YARN_VERSION

# Create cache directory
RUN mkdir -p /cache/yarn

# Copy yarn.lock, package.json, .yarnrc.yml, and .yarn directory
COPY .yarn/releases ./.yarn/releases 
COPY yarn.lock package.json .yarnrc.yml ./ 

# Use buildkit to mount cache for faster builds
RUN --mount=type=cache,target=/cache/yarn \
    yarn install

# Install pino-pretty globally
RUN npm install -g pino-pretty

# Copy the current directory contents into the container
COPY . .

# Run the command inside your image filesystem
CMD ["yarn", "start:debug"]
